___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1



#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [18]:
import numpy as np

Вивести версію та конфігурацію бібліотеки:

In [8]:
print(np.__version__)
np.show_config()


1.20.2
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


Створити вектор з 10 елементів, заповнений одиницями:

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Створити вектор із значеннями від 0 до 10:

In [10]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Створити матрицю 5 на 5, заповнену нулями:

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [45]:
Z = np.random.randint(0, 100, 20)
print(Z)

nz = np.nonzero(Z)
print(nz)

[77  1 72 46 52 69 29 59 66 28 85 57 62 73 13 50 45 67 99 45]
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19], dtype=int64),)


Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [46]:
m = np.mean(Z)
print(m)

md = np.median(Z)
print(md)

sv = np.std(Z)
print(sv)

54.75
58.0
23.304237812037535


Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [19]:
p = np.dot(np.random.random((4,2)), np.random.random((2,2)))
print(p)

[[0.02235798 0.09015206]
 [0.13632022 1.01007648]
 [0.15419967 0.95127054]
 [0.15470735 1.16094862]]


Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

In [20]:
np.reshape(p, 8)

array([0.02235798, 0.09015206, 0.13632022, 1.01007648, 0.15419967,
       0.95127054, 0.15470735, 1.16094862])

In [21]:
pmin, pmax = p.min(), p.max()
print(pmin, pmax)

0.022357981519856802 1.160948620971


In [22]:
p[np.where(p == p.max())] = 0
print(p)
print()

[[0.02235798 0.09015206]
 [0.13632022 1.01007648]
 [0.15419967 0.95127054]
 [0.15470735 0.        ]]



Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

In [14]:
print(np.corrcoef(p))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Дано матрицю. Знайти ранг матриці:

In [48]:
a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])

from numpy import linalg as LA
LA.matrix_rank(a)


3

Знайти визначник матриці:

In [49]:
from numpy import linalg as LA
LA.det(a)

440.0000000000002

Знайти власні значення та власні вектори матриці: 

In [60]:
w, v = np.linalg.eig(a)
print (w, v)

[14.13520334+0.j         -4.56760167+3.20389947j -4.56760167-3.20389947j] [[ 0.43131913+0.j         -0.31386258-0.47450898j -0.31386258+0.47450898j]
 [ 0.41502436+0.j         -0.07049527+0.4090732j  -0.07049527-0.4090732j ]
 [ 0.8010734 +0.j          0.7099444 +0.j          0.7099444 -0.j        ]]


Знайдіть число, що найчастіше зустрічається в масиві:

In [38]:
a = np.random.randint(0,10,50)
print(np.bincount(a).argmax())

1


Виведіть лише парні числа, що діляться на 5:

In [78]:
a = np.random.randint(0,10,50)

Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [17]:
import numpy as np 
from numpy import linalg as LA

a = [[2, 5],
    [1, -10]]

b = [1, 3]

x = LA.solve(a, b)
x

array([ 1. , -0.2])